equipment:
  id: P-N2-136
  testerId: P-N2-136
  type: P-N4
  tsId: ts
  testEqp: testEqp
  proberUrl: http://10.8.23.224:8088/matrix/sendMsg
  testerUrl: http://10.8.61.33：4444/matrix/sendMsg
client :
  recipeBodyUrl: http://localhost:5000/api/DeviceOperate
rcm:
  rcmUrl:

server:
  port: 8083
  servlet:
    session:
      timeout: 18000m
  tomcat:
    uri-encoding: UTF-8
    max-connections: 5000   #最大并发数
    accept-count: 200   #可以放到处理队列中的请求数
    connection-timeout: 2000ms
    threads:
      max: 800  #最大并发数
      min-spare: 80  #初始化时创建的线程数

spring:
  redis:
    host: 127.0.0.1
    port: 6379
    lettuce:
      pool:
        min-idle: 10
        max-idle: 50
        max-active: 100
  rabbitmq:
    host: 10.7.9.100
    port: 5672
    username: cluster_admin
    password: Usc.0123
    virtualHost: /
    timeout: 60000
    simple:
      acknowledge-mode: manual
    mes:
       queue: CP-MES-MQ
       exchange: MES
    client:
      queue: CLIENT-QUEUE.${equipment.id}
      exchange: CLIENT
    eap:
      checkName: false
      queue: TOTA1.EAP.${equipment.id}
      exchange: EAP
    rms:
      checkFlag: true
      queue: TOTA.RMS1
      exchange: RMS
    ems:
      checkFlag: false
      queue: GS.TEST.EIB
      exchange: EAPTEST
    rcm:
      queue: RCM.SERVER
      exchange: RCM
logging:
  config: classpath:log/log4j2-dev.xml
  level:
    cn.jay.repository: trace


number:
  max: 5

time:
  max: 4


GPIB:
  address: 1

tcp:
  timeout: 30  # 同步通信等待时间，单位：秒
  server:
    ip: 10.8.61.210
    port: 7000
  client:
    separator: \n  #分隔符
    retry:
      delay: 5    #TCP重连间隔时间，单位：秒
ftp:
  host: localhost
  port: 21
  user: administrator
  password: 123
  path: /D/ftp文件共享
  waferIdPath: /D/FTP共享
