license.path: /opt/eap/${eap.name}/config/license.key
server:
  port: 8083
  servlet:
    session:
      timeout: 18000m
  tomcat:
    uri-encoding: UTF-8
    max-connections: 5000   #最大并发数
    accept-count: 200   #可以放到处理队列中的请求数
    connection-timeout: 2000ms
    threads:
      max: 800  #最大并发数
      min-spare: 80  #初始化时创建的线程数



spring:
  redis:
#    host: 200.73.11.164
    host: localhost
    port: 6379
    lettuce:
      pool:
        min-idle: 10
        max-idle: 50
        max-active: 100
  rabbitmq:
    mes:
       host: 127.0.0.1
       port: 5672
       username: guest
       password: guest
       virtualHost: /
       timeout: 30000
       mesMq:
       eapMq:
       mesExchange:
       eapExchange:
       simple:
         acknowledge-mode: manual
    client:
      host: 127.0.0.1
      port: 5672
      username: guest
      password: guest
      virtualHost: /
      timeout: 30000
      listener:
      clientMq:
      serverMq:
      logMq:
      clientExchange:
      serverExchange:

      simple:
        acknowledge-mode: manual
logging:
  config: classpath:log/logback-dev.xml
  level:
    cn.jay.repository: trace

super:
  user:
    username: admin
    password: 123



async:
  thread:
    core_pool_size: 100
    max_pool_size:  1000
    queue_capacity: 200
    keep_alive_seconds: 30

webSocket:
  enable: true


version: @project.version@
